### ISSUE TITLE
virt-manager/QEMU: Could not read from CDROM (code 0009) on booting image

### ISSUE THREAD

**Issue by Laeeth** [symmetryinvestments/zfs-on-root-installer#1]
https://wiki.osdev.org/Bare_Bones

> I get Boot failed: Could not read from CD-ROM (code 0009) when trying to boot the iso image in QEMU
>     If your development system is booted from EFI it may be that you don't have the PC-BIOS version of the grub binaries installed anywhere. If you install them then grub-mkrescue will by default produce a hybrid ISO that will work in QEMU. On Ubuntu this can be achieved with: apt-get install grub-pc-bin. 
===
adding grub-pc-bin to packages.txt does not help.

**Comment by hamishcoleman** [comment]
The documentation needs improving to make this clear, but this installer only works on a EFI booting system - when booting with QEMU, it requires extra options to load a EFI system.

(I know we discussed this in person, but I wanted to be sure to write it down for the archives)
