### ISSUE TITLE
please default to vga console as well as serial

### ISSUE THREAD

**Issue by Laeeth** [symmetryinvestments/zfs-on-root-installer#7]
eg startup.nsh:
linux.efi initrd=initrd console=tty0 console=ttyS0,9600n8

**Comment by hamishcoleman** [comment]
In an attempt to keep the installer easy to use for non experts, the installer environment was deliberately configured to not send the linux kernel console messages to the VGA screen.

The assumption was that if a server was being installed, then we would have a IPMI serial console access - and might want to see the kernel boot messages, but if a desktop was being installed, this would be significantly less relevant.  

If you are looking for a login shell at the VGA screen, there is one to be found on virtual terminal 2.

If you just want to run the installer from the VGA screen, this will be done automatically  when you quit from the default htop display.
